#!/usr/bin/env python
from __future__ import print_function

import os
import sys
import transmissionrpc


def output():
    tc = transmissionrpc.Client('10.0.0.3', port=9091)
    stats = tc.session_stats()
    print('up.value', stats.uploadSpeed)
    print('down.value', stats.downloadSpeed)

def config():
    print('graph_title Transmission Speeds')
    print('graph_category transmission')
    print('up.label Up')
    print('down.label Down')

if len(sys.argv) == 2 and sys.argv[1] == 'config':
    config()
else:
    output()


