#!/usr/bin/env python
from __future__ import print_function

import os
import sys
from datetime import timedelta

import transmissionrpc

def output():
    tc = transmissionrpc.Client('10.0.0.3', port=9091)

    totalEta = 0
    longestEta = 0
    activeTorrents = 0
    
    torrents = tc.info().values()

    for torrent in torrents:
        if torrent.status != 'downloading':
            continue
        if not torrent.eta:
            continue
        activeTorrents += 1
        seconds = torrent.eta.seconds + torrent.eta.days * 60 * 60 * 24
        totalEta += seconds
        if seconds > longestEta:
            longestEta = seconds

    longestEta = float(longestEta) / 60 / 60 / 24
    totalEta = float(totalEta) / 60 / 60 / 24
    print('longest.value', longestEta)
    print('average.value', totalEta / activeTorrents)

def config():
    print('graph_title Transmission ETA')
    print('graph_category transmission')
    print('graph_vlabel Days')
    print('graph_args --rigid --lower-limit 0 --upper-limit 10')
    print('graph_scale no')
    print('longest.label Longest')
    print('average.label Average')

if len(sys.argv) == 2 and sys.argv[1] == 'config':
    config()
else:
    output()




