#!/usr/bin/env python
from __future__ import print_function

import os
import sys
import transmissionrpc

FIELDS = [
    'peersSendingToUs',
    'peersGettingFromUs',
    'peersConnected',
]

def output():
    tc = transmissionrpc.Client('10.0.0.3', port=9091)

    data = {}

    for field in FIELDS:
        data[field] = 0

    for id, torrent in tc.info().items():
        for field in FIELDS:
            data[field] += torrent.fields[field]

    for field in FIELDS:
        print('%s.value' % field, data[field])

def config():
    print('graph_title Transmission Total Peers')
    print('graph_category transmission')
    print('peersGettingFromUs.label GettingFromUs')
    print('peersSendingToUs.label SendingToUs')
    print('peersConnected.label Connected')

if len(sys.argv) == 2 and sys.argv[1] == 'config':
    config()
else:
    output()




